### ISSUE TITLE
but can you share data pls

### ISSUE THREAD

**Issue by Sandy4321** [vikas9087/MachineLearning-OperationsResearch-SupplyChainOptimization#1]
great code thanks
but can you share data pls
also is it possible to use PuLP

**Comment by vikas9087** [comment]
Hi @Sandy4321. Thanks for the feedback.

1. **Using PuLP**- Yes, indeed it's possible to use PuLP. I am including a couple of Medium article here ( [First](https://towardsdatascience.com/linear-programming-and-discrete-optimization-with-python-using-pulp-449f3c5f6e99), [Second](https://medium.com/opex-analytics/optimization-modeling-in-python-pulp-gurobi-and-cplex-83a62129807a) ). Please go through these to understand how to use PuLP and different solvers.
2. **Sharing Data**- Yes, I can share the data. Let me work on tweaking the data and then you can work on it.

If I can help you in any other way, please let me know.

Best Regards
Vikas

**Comment by vikas9087** [comment]
@Sandy4321 I have included the data files in the repository.

**Comment by Sandy4321** [comment]
great 
thanks for soon answer and data 
Using PuLP- Yes, indeed it's possible to use PuLP
yes it would be great to record all on PuLP since guroby is not available for vast majority 
by the way does PuLP has the same capabilities as guroby for this kind of task?
